#!/bin/sh
GOSH="$1"
LIB="$2"
EXE="$3"
SCRIPT="$4"
echo '#!/bin/sh' > $SCRIPT.sh && \
echo "exec $GOSH -I$LIB $EXE/$SCRIPT.scm" ' $@' >> scripts/$SCRIPT.sh && \
mv scripts/$SCRIPT.sh scripts/$SCRIPT && \
chmod +x scripts/$SCRIPT
