;; -*- mode: scheme; coding: utf-8 -*-
(allow-module rfc.uri)
(allow-module util.list)
(allow-module www.cgi)
(allow-module gauche.threads)
(allow-module srfi-11)
(allow-module rfc.822)
(allow-module sxml.ssax)
(allow-module sxml.sxpath)
(allow-module util.match)
